CPP = g++

a_ds001 : ds001.CPP
	$(CPP) -o $@ $^
a_ds002 : ds002.CPP
	$(CPP) -o $@ $^
a_ds003 : ds003.CPP
	$(CPP) -o $@ $^
a_ds004 : ds004.CPP
	$(CPP) -o $@ $^
a_ds005 : ds005.CPP
	$(CPP) -o $@ $^
a_ds006 : ds006.CPP
	$(CPP) -o $@ $^
a_ds007 : ds007.CPP
	$(CPP) -o $@ $^
a_ds008 : ds008.CPP
	$(CPP) -o $@ $^

clean :
	rm *.exe
	
